<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <Platforms>x64</Platforms>
    <AssemblyName>FlagInjector</AssemblyName>
    <RootNamespace>FlagInjector</RootNamespace>
  </PropertyGroup>
</Project>
